# Generated by Django 2.2.4 on 2019-09-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0002_daumrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_num', models.IntegerField(default=0)),
                ('rank_title', models.CharField(max_length=144)),
            ],
        ),
    ]
