# Generated by Django 2.2.4 on 2019-09-25 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0003_googlerank'),
    ]

    operations = [
        migrations.AddField(
            model_name='daumrank',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlerank',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='naverrank',
            name='url',
            field=models.URLField(default=datetime.datetime(2019, 9, 25, 8, 15, 39, 614243, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
